package com.travel.util;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.travel.pojo.Menu;

public class PhpFileContent {
	//private static Logger logger = LoggerFactory.getLogger(PhpFileContent.class);
	public static String phpSingleHtmlContent(String fromP, String toP,
			String fromCode, String toCode,String country) {
		String keyWords = getKeyWords(fromP,toP,country);
		 
		StringBuffer sbr = new StringBuffer("");
		String content = fromP + "至" + toP;
		sbr.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
		sbr.append("\n");
		sbr.append(" <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
		sbr.append("\n");
		sbr.append("<html dir=\"ltr\" lang=\"zh\" xml:lang=\"zh\" xmlns=\"http://www.w3.org/1999/xhtml\">");
		sbr.append("\n");
		sbr.append("<head>");
		sbr.append("\n");
		sbr.append("<title> " + keyWords + " </title>");
		sbr.append("\n");
		sbr.append("<meta name=\"Description\" content=\"www.e-traveltochina.com （美中机票网）以批发价格提供"
				+ content + "特价机票\" />");
		sbr.append("\n");
		sbr.append(" <meta name=\"Keywords\" content=\""+keyWords+ "\" />");
		sbr.append("\n");
		sbr.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
		sbr.append("\n");
		sbr.append("<style type=\"text/css\">");
		sbr.append("\n");
		sbr.append("html, body, div, iframe { margin:0; padding:0; height:100%; }");
		sbr.append("\n");
		sbr.append(" </style>");
		sbr.append("\n");
		sbr.append("</head>");
		sbr.append("\n");
		sbr.append("<body scroll=\"no\" >");
		sbr.append("\n");
		sbr.append("<div>");
		sbr.append("\n");
		sbr.append("<iframe src=\"../"
				+ fromCode.toLowerCase()
				+ "_"
				+ toCode.toLowerCase()
				+ "_"
				+ "price.php?fromCode="
				+ fromCode
				+ "&toCode="
				+ toCode
				+ "&fromP="
				+ fromP
				+ "&toP="
				+ toP
				+"&country="
				+country
				+ "\" frameBorder=\"0\"  height=\"100%\" width=\"100%\" scroll=\"no\" >");
		sbr.append("\n");
		sbr.append("</iframe>");
		sbr.append("\n");
		sbr.append("</div>");
		sbr.append("\n");
		sbr.append("</body>");
		sbr.append("\n");
		sbr.append("<script type=\"text/javascript\">");
		sbr.append("\n");
		sbr.append("var _gaq = _gaq || [];");
		sbr.append("\n");
		sbr.append("_gaq.push(['_setAccount', 'UA-25112573-2']);");
		sbr.append("\n");
		sbr.append(" _gaq.push(['_trackPageview']);");
		sbr.append("\n");
		sbr.append("(function() {");
		sbr.append("\n");
		sbr.append(" var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;");
		sbr.append("\n");
		sbr.append(" ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';");
		sbr.append("\n");
		sbr.append("var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);");
		sbr.append("\n");
		sbr.append("})();");
		sbr.append("\n");
		sbr.append("</script>");
		sbr.append("\n");
		sbr.append(" </html>");

		return sbr.toString();
	}

	public static String commonRequestPhp(String fromP, String toP,
			String fromCode, String toCode,String country,List<Menu> commentList) {
		String keyWords = getKeyWords(fromP,toP,country);
		String comment = "";
		for(int i = 0 ; i < commentList.size() ; i++){
			Menu menu = commentList.get(i);
			 //int count = i+1;
			comment += "<p style=\"padding-bottom: 11px; margin-top: 0px; padding-left: 20px; width: 930px;line-height:20px;"
					+ " margin-bottom: 0px; padding-top: 0px\"> <font color=\"#000000\" size=\"2\" face=\"宋体\">"+menu.getDescription()+"</font></p>";
		}
		//logger.info("size==="+commentList.size());
	//	logger.info("comment======"+comment);
		
		StringBuffer sbr = new StringBuffer("");
		sbr.append("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
		sbr.append("\n");
		sbr.append("<html xmlns=\"http://www.w3.org/1999/xhtml\">");
		sbr.append("\n");
		sbr.append("<head>");
		sbr.append("\n");
		sbr.append(" <meta name=\"Keywords\" content=\""+keyWords+ "\" />");
		sbr.append("\n");
		sbr.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />");
		sbr.append("\n");
		sbr.append("<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/style.css\" />");
		sbr.append("\n");
		sbr.append("<script src=\"js/jquery-1.4.2.js\"></script>");
		sbr.append("\n");
		sbr.append("<script>");
		sbr.append("\n");
		sbr.append("//$(function(){");
		sbr.append("\n");
		sbr.append("//$.ajax({");
		sbr.append("\n");
		sbr.append(" //type:'GET',");
		sbr.append("\n");
		sbr.append("//url : '/v1/menu/get_commnet1.json',");
		sbr.append("\n");
		sbr.append("//data : {");
		sbr.append("\n");
		sbr.append("//fromCode :'"+fromCode+"',");
		sbr.append("\n");
		sbr.append("//toCode :'"+toCode+"'");
		sbr.append("\n");
		sbr.append("//},");
		sbr.append("\n");
		sbr.append("//success:function(result){");
		sbr.append("\n");
		sbr.append("//var htmlTemp = document.getElementById('introduction-div').innerHTML;");
		sbr.append("\n");
		sbr.append("//for(var key in result){");
		sbr.append("\n");
		sbr.append("//var keyTepm=0;");
		sbr.append("\n");
		sbr.append("//keyTemp= 11+parseInt(key);");
		sbr.append("\n");
		sbr.append("//if(key == 0){htmlTemp +='&nbsp;&nbsp;<p style=\"padding-bottom:11px;margin-top:-28px;padding-left:20px;width:930px;margin-bottom: 0px; padding-top: 0px;font-size: 13px; font-family:-webkit-body\">'+keyTemp+'）'+result[key].description+'</p>';}else{");
		sbr.append("//htmlTemp +='&nbsp;&nbsp;<p style=\"padding-bottom:11px;margin-top:-8px;padding-left:20px;width:930px;margin-bottom: 0px; padding-top: 0px;font-size: 13px; font-family:-webkit-body\">'+keyTemp+'）'+result[key].description+'</p>';}");
		sbr.append("\n");
		sbr.append("//}");
		sbr.append("\n");
		sbr.append("//$('#introduction-div').html(htmlTemp);");
		sbr.append("\n");
		sbr.append("//},");
		sbr.append("\n");
		sbr.append("//error:function(){}");
		sbr.append("\n");
		sbr.append("//});");
		sbr.append("\n");
		sbr.append("//});");
		sbr.append("\n");
		sbr.append("</script>");
		sbr.append("\n");
		sbr.append("<script src=\"js/util.js\"></script>");
		sbr.append("\n");
		sbr.append("<script>");
		sbr.append("\n");
		sbr.append("var fromCode ='"+fromCode.trim()+"';");
		sbr.append("\n");
		sbr.append("var toCode = '"+toCode.trim()+"';");
		sbr.append("\n");
		sbr.append("var fromP = '"+fromP.trim()+"';");
		sbr.append("\n");
		sbr.append("var toP = '"+toP.trim()+"';");
		sbr.append("\n");
		sbr.append("var country = '"+country.trim()+"';");
		sbr.append("\n");
		sbr.append("</script>");
		sbr.append("\n");
		sbr.append("</head>");
		sbr.append("\n");
		sbr.append("<body>");
		sbr.append("\n");
		sbr.append(" <?php $fromCodePhp = '"+fromCode.trim()+"';");
		sbr.append("\n");
		sbr.append(" 		$toCodePhp = '"+toCode.trim()+"';");
		sbr.append("\n");
		sbr.append(" 		$fromP = '"+fromP.trim()+"';");
		sbr.append("\n");
		sbr.append(" 		$toP = '"+toP.trim()+"';");
		sbr.append("\n");
		sbr.append("        $country = '"+country.trim()+"';");
		sbr.append("\n");
		sbr.append(" ?>");
		sbr.append("\n");
		sbr.append("<a name=FLIGHT></a>");
		sbr.append("\n");
		sbr.append("<div id=\"maincontainer\">");
		sbr.append("\n");
		sbr.append("  <?php $language = '0';  require(\"top.php\");?>");
		sbr.append("\n");
		sbr.append("  <div id=\"content_area\">");
		sbr.append("\n");
		sbr.append("    <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"vertical-align: text-top; \">");
		sbr.append("\n");
		sbr.append("        <tr>");
		sbr.append("\n");
		sbr.append("      ");
		sbr.append("\n");
		sbr.append("      <td style=\"width:240px;\" valign=\"top\"><?php $language = '0';$from_param = $fromCodePhp;$to_param = $toCodePhp; $param_test = $country; require(\"menu.php\");?></td>");
		sbr.append("\n");
		sbr.append("      <td style=\"width:5px;\">&nbsp;</td>");
		sbr.append("\n");
		sbr.append("      <td  style=\"width:1000px;\" valign=\"top\"><table border=\"0\" cellspacing=\"0\" width=\"1000px\" cellpadding=\"0\" style=\"vertical-align: text-top;\">");
		sbr.append("\n");
		sbr.append("          <tr>");
		sbr.append("\n");
		sbr.append("            <td valign=\"top\" colspan=\"2\" style=\"padding-left:30px;\"><?php require(\"notice.php\");//通知公告?></td>");
		sbr.append("\n");
		sbr.append("          </tr>");
		sbr.append("\n");
		sbr.append("          <tr id=\"content_top\">");
		sbr.append("\n");
		sbr.append("            <td></td>");
		sbr.append("\n");
		sbr.append("          </tr>");
		sbr.append("\n");
		sbr.append("            <tr id=\"content_middle\">");
		sbr.append("\n");
		sbr.append("          ");
		sbr.append("\n");
		sbr.append("          <td valign=\"top\" colspan=\"2\" ><table cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%; height: 300px;\">");
		sbr.append("\n");
		sbr.append("             ");
		sbr.append("\n");
		sbr.append("              <tr>");
		sbr.append("\n");
		sbr.append("                <td>");
		sbr.append("\n");
		sbr.append("                  <table class=\"border\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 960px; height: 350px;\">");
		sbr.append("\n");
		sbr.append("                    <tr height=\"5\">");
		sbr.append("\n");
		sbr.append("                      <td colspan=\"3\" ></td>");
		sbr.append("\n");
		sbr.append("                    </tr>");
		sbr.append("\n");
		sbr.append("                    <tr>");
		sbr.append("\n");
		sbr.append("                      <td align=\"left\" style=\"width: 495px;padding-left:3px;\" valign=\"top\"><script type=\"text/javascript\" language=\"javascript\">  ");
		sbr.append("\n");
		sbr.append("									                  function IFrameReSize(iframename) {");
		sbr.append("\n");
		sbr.append("									                      var pTar = document.getElementById(iframename);");
		sbr.append("\n");
		sbr.append("									                      if (pTar) {//ff");
		sbr.append("\n");
		sbr.append("									                          if (pTar.contentDocument && pTar.contentDocument.body.offsetHeight) {");
		sbr.append("\n");
		sbr.append("									                              pTar.height = pTar.contentDocument.body.offsetHeight;");
		sbr.append("\n");
		sbr.append("									                          }else if(pTar.Document && pTar.Document.body.scrollHeight)");
		sbr.append("\n");
		sbr.append("									                          {//ie");
		sbr.append("\n");
		sbr.append("									                              pTar.height = pTar.Document.body.scrollHeight;");
		sbr.append("\n");
		sbr.append("									                          }");
		sbr.append("\n");
		sbr.append("									                      }");
		sbr.append("\n");
		sbr.append("									                  }");
		sbr.append("\n");
		sbr.append("									                  var flighturl = \"request_end.php?fromCode=\"+fromCode+\"&toCode=\"+toCode+\"&fromP=\"+fromP+\"&toP=\"+toP+\"&country=\"+country;");
		sbr.append("\n");
		sbr.append("									              </script>");
		sbr.append("\n");
		sbr.append("                        <iframe src=\"\" id=\"iframepage\" name=\"iframepage\" frameBorder=\"0\" scrolling=\"no\" width=\"960px\"  height=\"400px\"  onLoad=\"IFrameReSize('iframepage');\" ></iframe></td>");
		sbr.append("\n");
		sbr.append("                    <script>");
		sbr.append("\n");
		sbr.append("                    	document.getElementById(\"iframepage\").src=\"request_end.php?fromCode=\"+fromCode+\"&toCode=\"+toCode+\"&fromP=\"+fromP+\"&toP=\"+toP+\"&country=\"+country;");
		sbr.append("\n");
		sbr.append("                    </script>");
		sbr.append("\n");
		sbr.append("                    </tr>");
		sbr.append("\n");
		sbr.append("                  </table></td>");
		sbr.append("\n");
		sbr.append("              <tr style=\"height:10px;\">");
		sbr.append("\n");
		sbr.append("                <td>&nbsp;</td>");
		sbr.append("\n");
		sbr.append("              </tr>");
		sbr.append("\n");
		sbr.append("                </tr>");
		sbr.append("\n");
		sbr.append("              ");
		sbr.append("\n");
		sbr.append("              ");
		sbr.append("\n");
		sbr.append("                <td><?php ");
		sbr.append("\n");
		sbr.append("                                                    include_once \"./config.inc.php\";");
		sbr.append("\n");
		sbr.append("                                                    date_default_timezone_set (LOCAL_TIMEZONE);");
		sbr.append("\n");
		sbr.append("												");
		sbr.append("\n");
		sbr.append("										");
		sbr.append("\n");
		sbr.append("													?>");
		sbr.append("\n");
		sbr.append("                  <script type=\"text/javascript\">");
		sbr.append("\n");
		sbr.append("						function selectchang()");
		sbr.append("\n");
		sbr.append("						{");
		sbr.append("\n");
		sbr.append("							var FROM = fromCode;");
		sbr.append("\n");
		sbr.append("							//alert(FROM);");
		sbr.append("\n");
		sbr.append("							var TO = toCode;");
		sbr.append("\n");
		sbr.append("							//alert(TO);");
		sbr.append("\n");
		sbr.append("							var MONTH = <?php echo date('Ym');?>;");
		sbr.append("\n");
		sbr.append("							//alert(MONTH);");
		sbr.append("\n");
		sbr.append("							var STAYDAYS = document.getElementById(\"STAYDAYS\").value;");
		sbr.append("\n");
		sbr.append("							//alert(STAYDAYS);");
		sbr.append("\n");
		sbr.append("							var STOPS = \"0\";");
		sbr.append("\n");
		sbr.append("							//alert(STOPS);");
		sbr.append("\n");
		sbr.append("							document.getElementById(\"iframepage_calendar\").src = \"calendar_6m.php?lan=CN&from=\"+FROM+\"&to=\"+TO+\"&month=\"+MONTH+\"&staydays=\"+STAYDAYS+\"&stops=\"+STOPS+\"&title="
				+ fromP + "至" + toP + "特价机票\";");
		sbr.append("\n");
		sbr.append("							");
		sbr.append("\n");
		sbr.append("						}");
		sbr.append("\n");
		sbr.append("						</script>");
		sbr.append("\n");
		sbr.append("                  <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" align=\"center\">");
		sbr.append("\n");
		sbr.append("                    <tbody>");
		sbr.append("\n");
		sbr.append("                      <tr>");
		sbr.append("\n");
		sbr.append("                        <td height=\"5\" ><img border=\"0\" src=\"./images/content_line_bk.jpg\"  /></td>");
		sbr.append("\n");
		sbr.append("                      </tr>");
		sbr.append("\n");
		sbr.append("                    </tbody>");
		sbr.append("\n");
		sbr.append("                  </table>");
		sbr.append("\n");
		sbr.append("                  <table  cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%; height: 300px;\">");
		sbr.append("\n");
		sbr.append("                    <tr>");
		sbr.append("\n");
		sbr.append("                      <td><table class=\"border\" cellspacing=\"0\" cellpadding=\"0\" style=\"width: 100%; height: 30px;\">");
		sbr.append("\n");
		sbr.append("                          <tr>");
		sbr.append("\n");
		sbr.append("                            <td width=\"10px\">&nbsp;</td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"160px\" align=\"left\" style=\"display:none;\"><span style=\"font-size: 12px; font-weight: bold;\">始发城市</span>");
		sbr.append("\n");
		sbr.append("                              <select id=\"FROM\" name=\"FROM\" style=\"width: 100px;\">");
		sbr.append("\n");
		sbr.append("                                <option value=\"SFO\">San Francisco</option>");
		sbr.append("\n");
		sbr.append("                                <option value=\"LAX\">Los Angeles</option>");
		sbr.append("\n");
		sbr.append("                                <option value=\"SFO\">San Francisco</option>");
		sbr.append("\n");
		sbr.append("                              </select></td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"5px\"  style=\"display:none;\">&nbsp;</td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"180px\"  align=\"left\" style=\"display:none;\"><span style=\"font-size: 12px; font-weight: bold;\">目的地城市</span>");
		sbr.append("\n");
		sbr.append("                              <select id=\"TO\" name=\"TO\" style=\"width: 100px;\">");
		sbr.append("\n");
		sbr.append("                                <option value=\"CHA\">Beijing</option>");
		sbr.append("\n");
		sbr.append("                                <option value=\"SHA\">Shanghai</option>");
		sbr.append("\n");
		sbr.append("                              </select></td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"5px\" style=\"display:none;\">&nbsp;</td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"120px\"  align=\"left\" style=\"display:none;\"><span style=\"font-size: 12px; font-weight: bold;\">出发月份</span>");
		sbr.append("\n");
		sbr.append("                              <SELECT style=\"width:60px; font-size:12px;\" name=\"MONTH\" id=\"MONTH\" onchange=\"\"  >");
		sbr.append("\n");
		sbr.append("                                <?php ");
		sbr.append("\n");
		sbr.append("                                                    include_once \"./config.inc.php\";");
		sbr.append("\n");
		sbr.append("                                                    date_default_timezone_set (LOCAL_TIMEZONE);");
		sbr.append("\n");
		sbr.append("													$MonthText = array('一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月');");
		sbr.append("\n");
		sbr.append("													$cur_month = intval(date('m')); ");
		sbr.append("\n");
		sbr.append("													$cur_year = date('Y');");
		sbr.append("\n");
		sbr.append("													for($i=1;$i<=11;$i++)");
		sbr.append("\n");
		sbr.append("													{");
		sbr.append("\n");
		sbr.append("														if($cur_month <10)");
		sbr.append("\n");
		sbr.append("														{");
		sbr.append("\n");
		sbr.append("															echo '<OPTION value=\"'.$cur_year.'0'.($cur_month).'\">'.$MonthText[$cur_month-1].'</OPTION>';//$cur_month.$MonthText[$cur_month-1].'<br/>';");
		sbr.append("\n");
		sbr.append("														}");
		sbr.append("\n");
		sbr.append("														else");
		sbr.append("\n");
		sbr.append("														{");
		sbr.append("\n");
		sbr.append("															echo '<OPTION value=\"'.$cur_year.($cur_month).'\">'.$MonthText[$cur_month-1].'</OPTION>';//$cur_month.$MonthText[$cur_month-1].'<br/>';");
		sbr.append("\n");
		sbr.append("														}");
		sbr.append("\n");
		sbr.append("														");
		sbr.append("\n");
		sbr.append("														if($cur_month >=12)");
		sbr.append("\n");
		sbr.append("														{");
		sbr.append("\n");
		sbr.append("															$cur_month = $cur_month - 12;");
		sbr.append("\n");
		sbr.append("															$cur_year = $cur_year + 1;");
		sbr.append("\n");
		sbr.append("														}");
		sbr.append("\n");
		sbr.append("														$cur_month++;");
		sbr.append("\n");
		sbr.append("													}");
		sbr.append("\n");
		sbr.append("													?>");
		sbr.append("\n");
		sbr.append("                              </SELECT></td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"5px\" style=\"display:none;\">&nbsp;</td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"160px\"  align=\"left\"><span style=\"font-size: 12px; font-weight: bold;\">停留时间</span>");
		sbr.append("\n");
		sbr.append("                              <select id=\"STAYDAYS\" name=\"STAYDAYS\" style=\"width: 100px;\">");
		sbr.append("\n");
		sbr.append("");
		sbr.append("\n");
		sbr.append("                                <option selected=\"selected\" value=\"14\">两周内往返 </option>");
		sbr.append("\n");
		sbr.append("                                <option value=\"28\">一个月内往返 </option>");
		sbr.append("\n");
		sbr.append("                                <option value=\"91\">三个月内往返 </option>");
		sbr.append("\n");
		sbr.append("                                <option value=\"182\">半年内往返 </option>");
		sbr.append("\n");
		sbr.append("                              </select></td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"5px\">&nbsp;</td>");
		sbr.append("\n");
		sbr.append("                            <td width=\"120px\"  align=\"left\"  style=\"display:none;\"><span style=\"font-size: 12px; font-weight: bold;\">是否直飞</span>");
		sbr.append("\n");
		sbr.append("                              <select id=\"STOPS\" style=\"width: 40px;\">");
		sbr.append("\n");
		sbr.append("                                <option value=\"1\">是</option>");
		sbr.append("\n");
		sbr.append("                                <option selected=\"selected\" value=\"0\">否</option>");
		sbr.append("\n");
		sbr.append("                              </select></td>");
		sbr.append("\n");
		sbr.append("                            <td  align=\"left\"><a href=\"javascript:void(0);\"  onclick=\"selectchang();\" ><img border=\"0\" src=\"./images/search_flight.png\" /></a></td>");
		sbr.append("\n");
		sbr.append("                          </tr>");
		sbr.append("\n");
		sbr.append("                        </table></td>");
		sbr.append("\n");
		sbr.append("                    </tr>");
		sbr.append("\n");
		sbr.append("                    <tr height=\"335px\">");
		sbr.append("\n");
		sbr.append("                      <td colspan=\"3\" > ");
		sbr.append("\n");
		sbr.append("                      <iframe src=\"<?php");
		sbr.append("\n");
		sbr.append("                       echo 'calendar_6m.php?lan=CN&from='.$fromCodePhp.'&to='.$toCodePhp.'&stops=0&&staydays=14&title='.urlencode($fromP.'至'.$toP.'特价机票').'&month='.date('Ym');?>\" ");
		sbr.append("\n");
		sbr.append("                       id=\"iframepage_calendar\" name=\"iframepage_calendar\" frameBorder=\"0\" scrolling=\"no\" width=\"969px\"  height=\"1760px\"></iframe></td>");
		sbr.append("\n");
		sbr.append("                    </tr>");
		sbr.append("\n");
		sbr.append("                  </table>");
		sbr.append("\n");
		sbr.append("                  <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" align=\"center\">");
		sbr.append("\n");
		sbr.append("                    <tbody>");
		sbr.append("\n");
		sbr.append("                      <tr>");
		sbr.append("\n");
		sbr.append("                        <td height=\"5\" ><img border=\"0\" src=\"./images/content_line_bk.jpg\"  /></td>");
		sbr.append("\n");
		sbr.append("                      </tr>");
		sbr.append("\n");
		sbr.append("                    </tbody>");
		sbr.append("\n");
		sbr.append("                  </table>");
		sbr.append("\n");
		sbr.append("                  </td>");
		sbr.append("\n");
		sbr.append("              </tr>");
		sbr.append("\n");
		sbr.append("               <tr>");
		sbr.append("\n");
		sbr.append("                <td valign=\"top\" ><table width=\"100%\">");
		sbr.append("\n");
		sbr.append("                    <tbody>");
		sbr.append("\n");
		sbr.append("                      <tr id=\"tr_right_Chinese\">");
		sbr.append("\n");
		sbr.append("                        <td colspan=\"2\"><div id='introduction-div'><p style=\"padding-bottom: 18px; margin-top: 0px; padding-left: 20px; width: 930px;line-height:20px;");
		sbr.append("\n");
		sbr.append("                                                                margin-bottom: 0px; padding-top: 8px\"> <font color=\"#004483\" size=\"3\" face=\"微软雅黑\">美中机票网评论: "
				+ fromP + "到" + toP + "航班</font></p>");
		sbr.append("\n");
		sbr.append(comment);
		
		sbr.append("\n");
		sbr.append("                          <p style=\"padding-bottom: 11px; margin-top: 0px; padding-left: 20px; width: 930px;");
		sbr.append("\n");
		sbr.append("                                                                margin-bottom: 0px; padding-top: 0px\"> </p></div></td>");
		sbr.append("\n");
		sbr.append("                      </tr>");
		sbr.append("\n");
		sbr.append("                    </tbody>");
		sbr.append("\n");
		sbr.append("                  </table></td>");
		sbr.append("\n");
		sbr.append("              </tr>");
		sbr.append("\n");
		sbr.append("            </table>");
		sbr.append("\n");
		sbr.append("            <table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" align=\"center\">");
		sbr.append("\n");
		sbr.append("              <tbody>");
		sbr.append("\n");
		sbr.append("                <tr>");
		sbr.append("\n");
		sbr.append("                  <td height=\"5\"></td>");
		sbr.append("\n");
		sbr.append("                </tr>");
		sbr.append("\n");
		sbr.append("              </tbody>");
		sbr.append("\n");
		sbr.append("            </table></td>");
		sbr.append("\n");
		sbr.append("            </tr>");
		sbr.append("\n");
		sbr.append("          ");
		sbr.append("\n");
		sbr.append("          <tr id=\"content_bottom\">");
		sbr.append("\n");
		sbr.append("            <td>&nbsp;</td>");
		sbr.append("\n");
		sbr.append("          </tr>");
		sbr.append("\n");
		sbr.append("        </table></td>");
		sbr.append("\n");
		sbr.append("        </tr>");
		sbr.append("\n");
		sbr.append("      ");
		sbr.append("\n");
		sbr.append("    </table>");
		sbr.append("\n");
		sbr.append("  </div>");
		sbr.append("\n");
		sbr.append("  <?php require(\"footer.php\");?>");
		sbr.append("\n");
		sbr.append("</div>");
		sbr.append("\n");
		sbr.append("</body>");
		sbr.append("\n");
		sbr.append("</html>");
		sbr.append("\n");
		
		sbr.append("\n");
		return sbr.toString();
	}
	
	public static String getDefaultComments(String fromP,String toP){
		StringBuffer sbr = new StringBuffer("");
		sbr.append("1) 直飞： 美国联合航空公司 (United Airlines) 和中国东方航空公司 (China Eastern) 执行"+fromP+"至"+toP+"直飞航班。");
		sbr.append("\n");
		sbr.append("2) 机型： 东航航执飞"+fromP+"至"+toP+"航班的机型为空客330；美联航执飞"+fromP+"至"+toP+"航班的机型为波音747。");
		sbr.append("\n");
		sbr.append("3) 机场： 东航"+fromP+"至"+toP+"直飞航班运营机场为"+fromP+"国际机场；美联航"+fromP+"至"+toP+"直飞航班运营机场为"+fromP+"国际机场。");
		sbr.append("\n");
		sbr.append("4) 航班： 东航执飞"+fromP+"至"+toP+"直飞航班每日运营1班；美联航执飞"+fromP+"至"+toP+"直飞航班每日1班 。");
		sbr.append("\n");
		sbr.append("5) 航班衔接： 东航中国国内航班衔接网络完善，绝大多数城市当日衔接；美联航美国国内及加拿大境内航班衔接网络极其完善，绝大多数城市当日衔接。");
		sbr.append("\n");
		sbr.append("6) 舱位布局： 东航"+fromP+"至"+toP+"直飞航班设头等、公务和经济舱三舱；美联航"+fromP+"至"+toP+"直飞航班设头等、公务和经济舱三舱。");
		sbr.append("\n");
		sbr.append("7) 其他线路： 美联航、达尔美 (Delta Airlines) 、美利坚 (American Airlines) 从"+fromP+"机场都可以飞往"+toP+"，可在美国境内（洛杉矶等）中转；也可以搭乘大韩、韩亚、国泰、日航、全日空、加航等在韩国、日本、香港和加拿大中转至"+toP+"或中国其他城市；也可以在"+fromP+"或西岸其它城市搭乘国航、东航、南航、海航等航空公司航班飞往"+toP+"或中国其他城市。");
		sbr.append("\n");
		sbr.append("8) 中转须知："+fromP+"飞"+toP+"中转时注意最好不要选择过夜航班；回程建议预留三个小时左右转机时间；加航对中国公民在加当日转机提供免签证服务。");
		sbr.append("\n");
		sbr.append("9) 价格：就"+fromP+"飞"+toP+"航班而言，通常来讲，1 月到3 月初（中国春节除外）、11 月到12 月初的价格最为便宜；4 月和5月、9 月和10 月其次；6 月中到9 月初、12 月中到1 月初和中国春节期间，价格最贵。行程在1个月以内的较便宜；1个月以上、3个月以内会贵一些；3个月以上、6个月以内更贵一些；6个月以上最贵");
		sbr.append("\n");
		sbr.append("10) 学生寒、暑假回国时，机票价格很高，在考试和放假日期确定后，尽量提前订票，尽量晚走、早回。探亲访友的旅客，最好选择在淡季出行，最好不要超过1个月。");
		return sbr.toString();
	}

	public static String getKeyWords(String fromP,String toP,String country){
		String keyWords = "";
		if("USA".equals(country)){
			keyWords = fromP
					+"至"+toP+"特价机票-美中机票网,北美华人购买机票首选网站";
		}else if("CA".equals(country)){
			keyWords = fromP+"至"+toP+"特价机票-加中机票网-加拿大华人购买机票首选网站";
		}else if("CN".equals(country)){
			keyWords = fromP+"至"+toP+"特价机票-美中机票网-中国人购买机票首选网站";
		}
		
		return keyWords;
	}
	public static void main(String[] args) {
		// CreateFile.createFile("d:/test.php", phpHtmlContent(""+toP+"","石家庄"));
	}
}
